spring.application.name=url-shortener

#To see HTML updates immediately on browser refresh without restarting the app
spring.thymeleaf.cache=false
#Data Source properties for Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener-db
spring.datasource.username=postgres
spring.datasource.password=abc123

#we have multiple options: update / create / validate based on different use cases
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Docker lifecycle management
spring.docker.compose.lifecycle-management=start_and_stop
